IF(WIN32)
	set(GLFW3_INCLUDE_DIR ${GLFW3_DIR}/include)

	FILE(GLOB GLFW3_LIBS ${CMAKE_SOURCE_DIR}/${GLFW3_DIR}/lib/*.lib)

	FILE(GLOB GLFW3_DLLS ${CMAKE_SOURCE_DIR}/${GLFW3_DIR}/bin/*.dll)

	SET(DLLS
		${DLLS}
		${GLFW3_DLLS})

	string(STRIP "${GLFW3_LIBS}" GLFW3_LIBS)
endif()